### ISSUE TITLE
Install failure on windows

### ISSUE THREAD

**Issue by codito** [solarnz/nose-watcher#2]
`pip install nose-watcher` throws following error during install

```
Collecting nose-watcher
  Downloading nose_watcher-0.1.3-py2.py3-none-any.whl
Collecting python-inotify==0.6-test (from nose-watcher)
  Downloading python-inotify-0.6-test.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\auser\AppData\Local\Temp\pip-build-d3fefn_7\python-inotify\setup.py", line 17, in <module>
        platform)
    Exception: inotify is linux-specific, and does not work on win32
```

**Comment by solarnz** [comment]
Sorry, node-watcher will only work on linux due to the dependency on python-inotify and inotify.
